### ISSUE TITLE
Adjustments reset after adding new transform

### ISSUE THREAD

**Issue by MaxVanDijck** [IliaLarchenko/albumentations-demo#10]
Any adjustments to the transform parameters get reset when adding another transformation in advanced mode, eg. brightness limit, contrast limit for RandomBrightnessContrast will be set back to (-0.20 -0. 20)

**Comment by IliaLarchenko** [comment]
Hi!

Thank you for raising this issue, and sorry for the late reply.
I see and can reproduce it - the current version of the service is stateless, and any change that you make will set to default everything that follows in the logic flow.

I don't see easy ways to fix it in the current version. The hard way requires bumping the version of Streamlit, which will lead to many code changes to be made. Currently, I don't actively develop or support this project, and the current version is frozen in a stable working state. But the next time when I release any significant update, I will take this issue into account.
