### ISSUE TITLE
File :"\src\app.py", line 55, in main  

### ISSUE THREAD

**Issue by Rishi5583** [IliaLarchenko/albumentations-demo#2]
File "src/app.py", line 55, in main
    data = A.ReplayCompose(transforms)(image=image)
AttributeError: module 'albumentations' has no attribute 'ReplayCompose'

**Comment by IliaLarchenko** [comment]
Hi!
What version of albumentations do you use?
Have you installed dependencies from requirements.txt?

**Comment by Rishi5583** [comment]
albumentations : 0.3.2

**Comment by IliaLarchenko** [comment]
You are using quite an old version of albumentations. I think the `ReplayCompose` method has not been implemented in 0.3.2. Please refer to the `requirements.txt` for correct versions.
Use `pip install -r requirements.txt` in the virtual environment or just install the correct version `albumentations==0.4.3`

**Comment by Rishi5583** [comment]
Yeah , actually I donot want to change my opencv version , so I did not installed from requirements.txt 
, now working fine perfectly changed albumentations , opencv version  . Btw very nice  cool project :). Thanks.
